//! Contract-importer tests -- 1:1 mirror of upstream
//! `end-to-end/src/e2e_nested_contract/importer.test.ts`.
//!
//! Exercises the ImportTest contract, which uses autogenerated interfaces to
//! call into the Test contract's functions.  Verifies that contract-to-contract
//! calls via imported interfaces work for: no-args calls, public fn calls from
//! private, and public fn calls from public.
//!
//! Run with:
//! ```bash
//! AZTEC_NODE_URL=http://localhost:8080 cargo test --test e2e_nested_contract_importer -- --ignored --nocapture
//! ```

#![allow(
    clippy::await_holding_lock,
    clippy::doc_markdown,
    clippy::expect_used,
    clippy::panic,
    clippy::print_stderr,
    clippy::similar_names,
    clippy::cast_possible_wrap,
    clippy::too_many_lines,
    dead_code,
    unused_imports
)]

use crate::common::*;

// ---------------------------------------------------------------------------
// Shared wallet (ImportTest + Test contracts are redeployed per test, matching
// upstream's `beforeEach`)
// ---------------------------------------------------------------------------

static WALLET: OnceCell<Option<(TestWallet, AztecAddress)>> = OnceCell::const_new();

async fn get_wallet() -> Option<&'static (TestWallet, AztecAddress)> {
    WALLET
        .get_or_init(|| async { setup_wallet(TEST_ACCOUNT_0).await })
        .await
        .as_ref()
}

// ---------------------------------------------------------------------------
// Per-test deployments
// ---------------------------------------------------------------------------

struct Deployed {
    importer_address: AztecAddress,
    importer_artifact: ContractArtifact,
    test_address: AztecAddress,
}

async fn deploy_importer_and_test(wallet: &TestWallet, from: AztecAddress) -> Option<Deployed> {
    let importer_artifact = load_import_test_artifact()?;
    let (importer_address, importer_artifact, _) =
        deploy_contract(wallet, importer_artifact, vec![], from).await;
    let (test_address, _test_artifact, _) =
        deploy_contract(wallet, load_test_contract_artifact(), vec![], from).await;
    Some(Deployed {
        importer_address,
        importer_artifact,
        test_address,
    })
}

// ===========================================================================
// Tests
// ===========================================================================

/// TS: calls a method no arguments
#[tokio::test]
#[ignore = "requires live node via AZTEC_NODE_URL"]
async fn calls_a_method_no_arguments() {
    let _guard = serial_guard();
    let Some((wallet, account)) = get_wallet().await else {
        return;
    };
    let Some(d) = deploy_importer_and_test(wallet, *account).await else {
        return;
    };

    let call = build_call(
        &d.importer_artifact,
        d.importer_address,
        "call_no_args",
        vec![abi_address(d.test_address)],
    );
    send_call(wallet, call, *account).await;
}

/// TS: calls a public function
#[tokio::test]
#[ignore = "requires live node via AZTEC_NODE_URL"]
async fn calls_a_public_function() {
    let _guard = serial_guard();
    let Some((wallet, account)) = get_wallet().await else {
        return;
    };
    let Some(d) = deploy_importer_and_test(wallet, *account).await else {
        return;
    };

    let call = build_call(
        &d.importer_artifact,
        d.importer_address,
        "call_public_fn",
        vec![abi_address(d.test_address)],
    );
    send_call(wallet, call, *account).await;
}

/// TS: calls a public function from a public function
#[tokio::test]
#[ignore = "requires live node via AZTEC_NODE_URL"]
async fn calls_a_public_function_from_a_public_function() {
    let _guard = serial_guard();
    let Some((wallet, account)) = get_wallet().await else {
        return;
    };
    let Some(d) = deploy_importer_and_test(wallet, *account).await else {
        return;
    };

    let call = build_call(
        &d.importer_artifact,
        d.importer_address,
        "pub_call_public_fn",
        vec![abi_address(d.test_address)],
    );
    send_call(wallet, call, *account).await;
}
